on: 
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:4.5.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install R packages
        run: |
          install2.r kableExtra crosstalk DT fs

      - name: Build site
        run: |
          cd contents
          quarto render
          mkdir ../docs
          cp -r ./_site/* ../docs/
      - name: Disable Jekyll processing
        run: touch ../docs/.nojekyll